spring:
  thymeleaf:
    cache: false
    prefix: "classpath:/templates/"
    suffix: .html
  redis:
    host: 192.168.159.128

sso:
  server:
    url: http://localhost:8090/login.html
server:
  port: 8091