spring:
  application:
    name: mall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8333
  session:
    store-type: redis
  redis:
    host: 192.168.159.128
server:
  port: 40000
mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10