server:
  port: 10001

spring:
  datasource:
    url: jdbc:mysql://192.168.159.128:3306/gulimall_pms
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: mall-product
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848ss
  # 指定返回时间的格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  cache:
    type: redis
    redis:
      key-prefix: cache_
      time-to-live: 36000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.myself.mall.product: debug