spring:
  datasource:
    url: jdbc:mysql://192.168.159.128:3306/gulimall_oms
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-order
  redis:
    host: 192.168.159.128
  rabbitmq:
    host: 192.168.159.128
    port: 5672
    # 指定虚拟主机
    #    virtual-host: /
    username: guest
    password: guest
    # 开启发送端确认
    publisher-confirm-type: correlated
    #　开启发送端消息抵达队列确认
    publisher-returns: true
    # 只要抵达队列，以异步优先回调我们这个 returnconfirm
    template:
      mandatory: true
    # 手动ack消息 消息不容易丢失
    listener:
      simple:
        acknowledge-mode: manual

myRabbitmq:
  MQConfig:
    eventExchange: order-event-exchange
    routingKey: order.release.order
    delayQueue: order.delay.queue
    queues: order.release.order.queue
    createOrder: order.create.order
    releaseOther: stock.release.stock.queue
    releaseOtherKey: order.release.other
    ttl: 60000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000

mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10